#!/bin/bash
################################################################################
# Quick Reference Card - Save This!
# Paste into terminal or print for your desk
################################################################################

# 📌 BOOKMARK THESE GITHUB URLS
echo "📚 Documentation Links:"
echo "  Main Repo: https://github.com/Nikhil-ig/group-assistant-v3"
echo "  Getting Started: https://github.com/Nikhil-ig/group-assistant-v3/blob/main/GETTING_STARTED.md"
echo "  Quick Start: https://github.com/Nikhil-ig/group-assistant-v3/blob/main/SYNC_QUICK_START.md"
echo "  Setup Guide: https://github.com/Nikhil-ig/group-assistant-v3/blob/main/VPS_DEPLOYMENT.md"
echo ""

# 🚀 QUICK START
echo "🚀 QUICK START:"
echo ""
echo "Step 1: SSH to VPS and run setup"
echo "  ssh root@your.vps.ip"
echo "  bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Nikhil-ig/group-assistant-v3/main/setup-vps.sh)\""
echo ""
echo "Step 2: Make changes on Mac and push"
echo "  cd '/Users/apple/Documents/Personal/startup/bots/telegram bot/python/main_bot_v2/v3'"
echo "  git add ."
echo "  git commit -m 'your message'"
echo "  git push origin main"
echo ""
echo "Step 3: VPS auto-deploys! 🎉"
echo ""

# 💻 COMMON COMMANDS
echo "═══════════════════════════════════════════════════════════════"
echo "💻 COMMON COMMANDS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "ON YOUR MAC:"
echo "  git status              - See what changed"
echo "  git add .               - Stage all changes"
echo "  git commit -m '...'     - Commit changes"
echo "  git push origin main    - Push to GitHub"
echo ""

echo "ON VPS (via SSH):"
echo "  ssh root@your.vps.ip                    - SSH to VPS"
echo "  docker compose ps                       - See all services"
echo "  docker compose logs -f                  - View live logs"
echo "  docker compose logs -f bot              - View bot logs only"
echo "  /opt/group-assistant-v3/deploy-vps.sh  - Manual deployment"
echo "  tail -f /var/log/group-assistant-deploy.log  - Deployment history"
echo ""

# 🔐 IMPORTANT
echo "═══════════════════════════════════════════════════════════════"
echo "🔐 IMPORTANT REMINDERS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ These files are ON VPS ONLY (never commit!):"
echo "   - bot/.env                     ← Your bot token"
echo "   - centralized_api/.env         ← Database passwords"
echo ""
echo "✅ These files ARE safe to commit:"
echo "   - bot/.env.example             ← Template"
echo "   - centralized_api/.env.example ← Template"
echo "   - setup-vps.sh                 ← Setup script"
echo "   - deploy-vps.sh                ← Deploy script"
echo "   - All .md documentation"
echo ""

# 🆘 TROUBLESHOOTING
echo "═══════════════════════════════════════════════════════════════"
echo "🆘 QUICK TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Services won't start:"
echo "  docker compose logs      # See the error"
echo "  docker compose down -v   # Clean up"
echo "  docker compose up -d     # Start fresh"
echo ""
echo "Code changes not deployed:"
echo "  /opt/group-assistant-v3/deploy-vps.sh  # Run manually"
echo "  tail -f /var/log/group-assistant-deploy.log  # Check log"
echo ""
echo "Webhook not working:"
echo "  sudo systemctl status webhook"
echo "  sudo journalctl -u webhook -f"
echo ""

# 📋 WORKFLOW
echo "═══════════════════════════════════════════════════════════════"
echo "📋 YOUR DAILY WORKFLOW"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Edit code in VS Code on your Mac"
echo "2️⃣  Commit: git commit -m 'your message'"
echo "3️⃣  Push: git push origin main"
echo "4️⃣  VPS auto-deploys (webhook) or within 5 min (cron)"
echo "5️⃣  Check: ssh root@your.vps.ip && docker compose ps"
echo ""

# 🎯 FILES CREATED
echo "═══════════════════════════════════════════════════════════════"
echo "🎯 FILES CREATED FOR YOU"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Automation:"
echo "  ✅ deploy-vps.sh                 (Deployment automation)"
echo "  ✅ setup-vps.sh                  (One-command VPS setup)"
echo "  ✅ webhook-receiver.sh           (GitHub webhook listener)"
echo ""
echo "Documentation:"
echo "  ✅ GETTING_STARTED.md            (Start here!)"
echo "  ✅ SYNC_QUICK_START.md           (1-2 min reference)"
echo "  ✅ VPS_DEPLOYMENT.md             (Complete guide)"
echo "  ✅ VISUAL_WORKFLOW.md            (Diagrams)"
echo "  ✅ SETUP_CHECKLIST.md            (Detailed steps)"
echo "  ✅ SYNC_SETUP_COMPLETE.md        (Summary)"
echo ""
echo "Templates:"
echo "  ✅ bot/.env.example              (Bot config)"
echo "  ✅ centralized_api/.env.example  (API config)"
echo ""
echo "Code:"
echo "  ✅ bot/main.py                   (Auto-loads .env)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✨ You're all set! Start syncing! 🚀"
echo "═══════════════════════════════════════════════════════════════"
